import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BadgeCheck, BookOpenCheck, Building2, CircleDot, GraduationCap, MonitorPlay, Rocket, School, Sparkles, UsersRound } from "lucide-react";
import { ProductTourTrigger } from "@/components/site/product-tour-trigger";
import { BreadcrumbStructuredData, ItemListStructuredData, WebPageStructuredData } from "@/components/site/structured-data";
import { industrySolutionPages } from "@/lib/industry-page-content";
import { solutionPages } from "@/lib/site-content";

export const metadata: Metadata = {
  title: "KASA LMS Solutions for Institutes, Academies, Trainers, and EdTech Teams",
  description: "See how KASA supports coaching institutes, online academies, trainers, EdTech startups, and skill development centres with one branded LMS platform.",
  alternates: { canonical: "/solutions" },
};

const audienceVisuals = [
  [School, "COACHING", "Batches, fees and academic operations", "#125cc9"],
  [Building2, "ACADEMIES", "Sell and deliver a complete digital academy", "#7c3aed"],
  [Sparkles, "CREATORS", "Turn expertise into your own product", "#e15b9a"],
  [Rocket, "EDTECH", "Move faster with a working foundation", "#16886f"],
  [GraduationCap, "SKILL CENTRES", "Structure training and completion proof", "#db7b24"],
] as const;

const operatingFlow = [["Attract", "Website, offers and enquiries"], ["Convert", "Pricing, counselling and payment"], ["Deliver", "Courses, classes and progress"], ["Prove", "Assessments and certificates"]] as const;

export default function SolutionsIndexPage() {
  const pages = solutionPages.map((page) => ({ ...page, href: `/solutions/${page.slug}` }));
  return <>
    <BreadcrumbStructuredData items={[{ name: "Home", href: "/" }, { name: "Solutions", href: "/solutions" }]} />
    <ItemListStructuredData name="KASA LMS Solutions" items={[...pages, ...industrySolutionPages.map((page) => ({ ...page, href: `/solutions/${page.slug}` }))]} />
    <WebPageStructuredData name="KASA LMS Solutions" description="Role and industry-specific LMS workflows for education businesses." href="/solutions" />
    <main className="overflow-hidden bg-[#fffdf9] text-[#17213c] dark:bg-[#081226] dark:text-white">
      <section className="relative px-4 pb-20 pt-28 sm:px-6 sm:pt-34 lg:px-8"><div className="absolute inset-x-0 top-0 h-[34rem] bg-[#edf4ff] dark:bg-[#0d2040]" /><div className="relative mx-auto max-w-7xl"><nav aria-label="Breadcrumb" className="flex items-center gap-2 text-xs font-medium text-slate-500 dark:text-slate-400"><Link href="/" className="hover:text-primary">Home</Link><span>/</span><span className="text-slate-900 dark:text-white">Solutions</span></nav><div className="mt-12 grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.2em] text-primary dark:text-emerald-200"><CircleDot className="size-3.5" />Find your operating model</p><h1 className="mt-5 font-heading text-4xl font-semibold leading-[1.04] tracking-[-.045em] sm:text-6xl">Your education business is not generic. Your LMS path should not be either.</h1><p className="mt-6 max-w-xl text-base leading-8 text-slate-600 sm:text-lg dark:text-slate-300">Start with the team you run today, the learners you serve, and the operating work you want to make easier. Then explore the KASA workflow built around that reality.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="#models" className="inline-flex h-12 items-center justify-center gap-2 rounded-full bg-primary px-6 text-sm font-semibold text-white shadow-xl shadow-blue-900/20">Choose your model <ArrowRight className="size-4" /></Link><ProductTourTrigger label="Discuss my setup" variant="outline" size="md" className="justify-center bg-white/70 dark:bg-white/[.06]" /></div></div><div className="relative border border-blue-950/10 bg-white p-4 shadow-[18px_18px_0_rgba(50,121,226,.15)] dark:border-white/10 dark:bg-[#10254a]"><div className="bg-[#0d2e5b] p-5 text-white sm:p-7"><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-200">One connected academy loop</p><div className="mt-7 grid gap-2 sm:grid-cols-4">{operatingFlow.map(([label, detail], index) => <div key={label} className="relative border border-white/12 bg-white/[.06] p-3"><span className="font-mono text-xs text-emerald-200">0{index + 1}</span><p className="mt-6 text-sm font-semibold">{label}</p><p className="mt-1 text-xs leading-5 text-blue-100">{detail}</p>{index < 3 ? <ArrowRight className="absolute -right-2.5 top-1/2 hidden size-5 bg-[#0d2e5b] p-1 text-emerald-200 sm:block" /> : null}</div>)}</div><p className="mt-5 border-t border-white/10 pt-5 text-sm leading-6 text-blue-100">KASA brings these moments into one branded system so the learner experience and internal operations do not drift apart.</p></div></div></div></div></section>
      <section id="models" className="scroll-mt-24 px-4 py-16 sm:px-6 sm:py-22 lg:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-4 border-b border-blue-950/10 pb-8 md:flex-row md:items-end md:justify-between dark:border-white/10"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-primary dark:text-emerald-200">Core solutions</p><h2 className="mt-3 font-heading text-3xl font-semibold sm:text-4xl">What does your team need to run better?</h2></div><p className="max-w-xl text-sm leading-7 text-slate-600 dark:text-slate-300">These are not feature categories. They are starting points for different kinds of education businesses.</p></div><div className="mt-8 space-y-3">{pages.map((page, index) => { const [Icon, label, outcome, color] = audienceVisuals[index]; return <Link key={page.href} href={page.href} className="group grid gap-5 border border-blue-950/10 bg-white p-5 transition hover:-translate-y-0.5 hover:shadow-xl hover:shadow-blue-950/8 sm:grid-cols-[5rem_1fr_auto] sm:items-center sm:p-7 dark:border-white/10 dark:bg-white/[.04]"><div className="grid size-14 place-items-center rounded-full text-white" style={{ backgroundColor: color }}><Icon className="size-6" /></div><div><p className="text-xs font-bold uppercase tracking-[.16em]" style={{ color }}>{label}</p><h3 className="mt-2 font-heading text-xl font-semibold sm:text-2xl">{page.title}</h3><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600 dark:text-slate-300">{outcome}</p></div><span className="inline-flex items-center gap-2 text-sm font-bold text-primary dark:text-emerald-200">Explore solution <ArrowRight className="size-4 transition group-hover:translate-x-1" /></span></Link>})}</div></div></section>
      <section className="bg-[#152645] px-4 py-18 text-white sm:px-6 sm:py-24 lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-10 lg:grid-cols-[.4fr_.6fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-200">What stays connected</p><h2 className="mt-4 font-heading text-3xl font-semibold leading-tight sm:text-4xl">One platform. Different views for the people who do the work.</h2><p className="mt-4 text-sm leading-7 text-blue-100">Learners, faculty, counsellors and administrators need different screens—but they should not be working from disconnected stories.</p></div><div className="grid gap-px bg-white/10 sm:grid-cols-2">{[[UsersRound, "Learners", "Courses, schedules, replays, tasks, progress and certificates."], [BookOpenCheck, "Faculty", "Assigned batches, class context, academic tasks and learner work."], [MonitorPlay, "Admissions", "Enquiries, course interest, follow-up and conversion context."], [BadgeCheck, "Admins", "Programs, people, payments, permissions and reporting."]].map(([Icon, role, text]) => { const RoleIcon = Icon as typeof UsersRound; return <div key={String(role)} className="bg-[#1b3157] p-6"><RoleIcon className="size-5 text-emerald-200" /><h3 className="mt-5 font-heading text-xl font-semibold">{String(role)}</h3><p className="mt-2 text-sm leading-6 text-blue-100">{String(text)}</p></div>})}</div></div></div></section>
      <section className="px-4 py-18 sm:px-6 sm:py-24 lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-5 md:grid-cols-[.35fr_.65fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-primary dark:text-emerald-200">Industry directory</p><h2 className="mt-3 font-heading text-3xl font-semibold leading-tight">Find a closer match for your teaching business.</h2></div><p className="self-end text-sm leading-7 text-slate-600 dark:text-slate-300">Explore industry-specific pages for different education and training models. Each one connects the business context to relevant KASA workflows.</p></div><div className="mt-9 grid border-l border-t border-blue-950/10 sm:grid-cols-2 lg:grid-cols-3 dark:border-white/10">{industrySolutionPages.map((page, index) => <Link key={page.slug} href={`/solutions/${page.slug}`} className="group flex min-h-35 flex-col justify-between border-b border-r border-blue-950/10 p-5 transition hover:bg-blue-50 dark:border-white/10 dark:hover:bg-white/[.05]"><span className="font-mono text-xs font-bold text-primary/50 dark:text-emerald-200/60">{String(index + 1).padStart(2, "0")}</span><div><h3 className="font-heading text-base font-semibold">{page.title}</h3><span className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-primary dark:text-emerald-200">Explore <ArrowRight className="size-3 transition group-hover:translate-x-1" /></span></div></Link>)}</div></div></section>
      <section className="px-4 pb-20 sm:px-6 sm:pb-24 lg:px-8"><div className="mx-auto max-w-7xl rounded-[2rem] bg-[linear-gradient(135deg,#d9f6ed,#edf4ff)] p-7 sm:p-10 dark:bg-[linear-gradient(135deg,#123c3a,#122b52)]"><div className="grid gap-8 lg:grid-cols-[.7fr_.3fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-primary dark:text-emerald-200">Make the next move clearer</p><h2 className="mt-3 font-heading text-3xl font-semibold sm:text-4xl">Map one active program before you migrate everything.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-600 dark:text-slate-300">Bring one course, one batch or one academy offer to a product walkthrough. We will help you identify the people, records and moments that need to stay connected.</p></div><ProductTourTrigger label="Plan my KASA setup" variant="solid" size="lg" className="justify-center" /></div></div></section>
    </main>
  </>;
}
