import Link from "next/link";
import {
  ArrowRight,
  Award,
  BadgeCheck,
  BookOpenCheck,
  CheckCircle2,
  ClipboardCheck,
  FileBadge2,
  FileCheck2,
  Fingerprint,
  GraduationCap,
  KeyRound,
  MessageCircleMore,
  PenLine,
  QrCode,
  RotateCcw,
  ShieldCheck,
  Sparkles,
  Target,
  UserRoundCheck,
} from "lucide-react";
import { ProductTourTrigger } from "@/components/site/product-tour-trigger";
import { CurrentDateLabel } from "@/components/site/resource-pages/current-date-label";
import { BreadcrumbStructuredData, FaqStructuredData, WebPageStructuredData } from "@/components/site/structured-data";
import type { PageSummary } from "@/lib/site-content";

const faqs: Array<[string, string]> = [
  ["Should every online course include a certificate?", "No. Issue a certificate only when the academy can clearly state what the learner did to earn it. A short orientation may need no credential, while a professional program may require lessons, attendance, assessment, submitted work, or manual review."],
  ["What is the difference between participation, completion, and achievement certificates?", "Participation confirms presence, completion confirms that defined program requirements were finished, and achievement confirms a stated performance standard. The title and wording should not imply stronger evidence than the academy actually collected."],
  ["Can video completion alone be used as the certificate rule?", "It can suit a simple self-paced awareness course, but opening or finishing videos does not prove understanding. For skill, compliance, or outcome-focused programs, combine content completion with a quiz, assignment, project, attendance, or review appropriate to the promise."],
  ["What information should a course certificate contain?", "Usually include the learner's verified name, credential type, program title, academy identity, issue date, authorised signatory, unique certificate ID, and—where useful—the completion criteria, duration, score, level, or verification route."],
  ["How should corrections or revoked certificates be handled?", "Keep the original issuance record, reason for change, actor, and timestamp. A corrected credential should receive controlled versioning, while a revoked credential should no longer verify as valid. Avoid silently replacing records without an audit trail."],
  ["Does a certificate guarantee employment, licensing, or government recognition?", "No. An academy certificate records what that academy has assessed or confirmed. Do not imply accreditation, licensing, employment eligibility, academic credit, or regulatory recognition unless the issuing organisation genuinely has that authority."],
];

const credentialLevels = [
  ["Participation", "Presence", "Attended a workshop, webinar, orientation, or live session.", "Attendance or approved participation record"],
  ["Completion", "Requirements", "Finished the defined learning path and required activities.", "Lessons + required task or attendance rule"],
  ["Achievement", "Performance", "Met a stated assessment, project, or demonstrated-skill threshold.", "Score, rubric, reviewed work, or practical evidence"],
] as const;

const ruleParts = [
  [BookOpenCheck, "Learning", "Required modules or lessons completed", "100% required content"],
  [UserRoundCheck, "Attendance", "Minimum live participation recorded", "At least 75%"],
  [ClipboardCheck, "Assessment", "Exam or quiz threshold achieved", "Score 70% or above"],
  [FileCheck2, "Application", "Assignment or project approved", "Faculty review: passed"],
] as const;

export function CourseCertificatesBestPracticesPage({ page }: { page: PageSummary }) {
  return <>
    <BreadcrumbStructuredData items={[{ name: "Home", href: "/" }, { name: "Resources", href: "/resources" }, { name: page.title, href: `/resources/${page.slug}` }]} />
    <WebPageStructuredData name={page.title} description={page.description} href={`/resources/${page.slug}`} pageType="Article" />
    <FaqStructuredData faqs={faqs} />

    <main className="overflow-hidden bg-[#f7f3ea] text-[#10233f] dark:bg-[#071225] dark:text-white">
      <section className="relative px-4 pb-14 pt-32 sm:px-6 sm:pt-36 lg:px-8">
        <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_12%_18%,rgba(204,150,64,.15),transparent_28rem),radial-gradient(circle_at_87%_20%,rgba(43,137,130,.13),transparent_30rem)]" />
        <div className="relative mx-auto max-w-7xl">
          <nav aria-label="Breadcrumb" className="flex items-center gap-2 text-xs font-medium text-slate-500 dark:text-slate-400"><Link href="/" className="hover:text-primary">Home</Link><span>/</span><Link href="/resources" className="hover:text-primary">Resources</Link><span>/</span><span className="text-[#10233f] dark:text-white">Certificate best practices</span></nav>
          <div className="mt-8 grid gap-10 lg:grid-cols-[.78fr_1.22fr] lg:items-center xl:gap-16">
            <div><div className="inline-flex items-center gap-2 rounded-full border border-[#9f772f]/20 bg-[#f1e4c8] px-3 py-1.5 text-[.68rem] font-semibold uppercase tracking-[.2em] text-[#76551e] dark:border-amber-200/15 dark:bg-amber-200/10 dark:text-amber-200"><FileBadge2 className="size-3.5" />Credential design guide</div><h1 className="mt-5 max-w-xl font-heading text-[2.4rem] font-semibold leading-[1.04] tracking-[-.045em] sm:text-5xl lg:text-[3.4rem]">A certificate should state <span className="text-[#287f78] dark:text-[#65d4c6]">what was earned</span>—and what proves it.</h1><p className="mt-6 max-w-xl text-base leading-8 text-slate-600 dark:text-slate-300">Design credible course certificates with clear eligibility rules, accurate wording, learner identity, branded issuance, and a record your academy can explain later.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><ProductTourTrigger label="Map my certificate workflow" variant="solid" size="sm" className="justify-center" /><Link href="/tools/certificate-generator" className="inline-flex h-10 items-center justify-center gap-2 rounded-full border border-[#10233f]/15 bg-white/65 px-5 text-sm font-semibold dark:border-white/15 dark:bg-white/5">Try certificate generator <ArrowRight className="size-4" /></Link></div></div>

            <div className="relative px-2 py-4 sm:px-7">
              <div className="absolute inset-0 rotate-2 rounded-[1.8rem] bg-[#14385f]/10 dark:bg-white/5" />
              <div className="relative border border-[#b59659]/35 bg-[#fffdf8] p-3 shadow-[0_32px_80px_-45px_rgba(33,43,64,.6)] dark:border-amber-200/20 dark:bg-[#f7f1e5] sm:p-5">
                <div className="border border-[#b59659]/40 p-5 text-center text-[#17304f] sm:p-8">
                  <div className="flex items-start justify-between text-left"><div className="grid size-11 place-items-center rounded-full bg-[#173f70] text-white"><Award className="size-6" /></div><div className="text-right"><p className="text-[.52rem] font-semibold uppercase tracking-[.22em] text-[#86704a]">Credential ID</p><p className="mt-1 font-mono text-[.62rem]">KASA-2026-00482</p></div></div>
                  <p className="mt-6 font-serif text-[.65rem] uppercase tracking-[.32em] text-[#9a7841]">Certificate of achievement</p><p className="mt-3 font-serif text-3xl font-semibold sm:text-4xl">Shivaan Gangwar</p><div className="mx-auto mt-3 h-px max-w-sm bg-[#b59659]/40" /><p className="mx-auto mt-4 max-w-md text-xs leading-6 text-slate-600">has successfully completed <strong className="text-[#17304f]">Applied Digital Marketing</strong> and met the published assessment and project requirements.</p>
                  <div className="mt-7 grid grid-cols-[1fr_auto_1fr] items-end gap-4"><div><div className="mx-auto h-px max-w-32 bg-[#17304f]/40" /><p className="mt-2 text-[.55rem] font-semibold uppercase tracking-[.13em]">Authorised signatory</p></div><div className="grid size-16 place-items-center rounded-full border-2 border-[#b59659] bg-[#f5ead2]"><BadgeCheck className="size-8 text-[#287f78]" /></div><div><p className="font-serif text-sm"><CurrentDateLabel /></p><div className="mx-auto mt-1 h-px max-w-32 bg-[#17304f]/40" /><p className="mt-2 text-[.55rem] font-semibold uppercase tracking-[.13em]">Date issued</p></div></div>
                  <div className="mt-6 flex items-center justify-between border-t border-[#b59659]/25 pt-3 text-[.55rem] text-slate-500"><span>Outcome · Assessment · Reviewed project</span><span className="flex items-center gap-1.5"><QrCode className="size-4" />Verify credential</span></div>
                </div>
              </div>
              <div className="absolute -bottom-1 right-0 hidden rounded-xl bg-[#10233f] px-4 py-3 text-white shadow-xl sm:block"><p className="text-[.55rem] uppercase tracking-[.15em] text-emerald-200">Status</p><p className="mt-1 flex items-center gap-2 text-xs font-semibold"><CheckCircle2 className="size-3.5 text-emerald-300" />Valid · requirements met</p></div>
            </div>
          </div>
        </div>
      </section>

      <section className="border-y border-[#10233f]/10 bg-white/65 px-4 py-14 sm:px-6 lg:px-8 dark:border-white/10 dark:bg-[#0a1930]">
        <div className="mx-auto max-w-7xl"><div className="grid gap-6 lg:grid-cols-[.34fr_.66fr] lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#287f78] dark:text-[#65d4c6]">Name the evidence honestly</p><h2 className="mt-3 font-heading text-3xl font-semibold leading-tight sm:text-4xl">Not every certificate makes the same claim.</h2></div><p className="max-w-3xl text-sm leading-7 text-slate-600 dark:text-slate-300">Choose the credential type after deciding what evidence the academy truly holds. Strong design cannot repair inflated wording.</p></div><div className="mt-8 grid gap-3 lg:grid-cols-3">{credentialLevels.map(([title, claim, use, evidence], index) => <article key={title} className="border border-[#10233f]/12 bg-[#fffdf8] p-5 dark:border-white/10 dark:bg-white/[.04]"><div className="flex items-center justify-between"><span className="font-mono text-[.62rem] text-[#287f78]">0{index + 1}</span><span className="rounded-full bg-[#d8eee9] px-2.5 py-1 text-[.58rem] font-semibold uppercase tracking-[.12em] text-[#22665f] dark:bg-emerald-300/10 dark:text-emerald-200">{claim}</span></div><h3 className="mt-7 font-heading text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{use}</p><div className="mt-5 border-t border-[#10233f]/10 pt-4 dark:border-white/10"><p className="text-[.58rem] font-semibold uppercase tracking-[.14em] text-slate-400">Minimum credible record</p><p className="mt-2 text-xs font-medium">{evidence}</p></div></article>)}</div></div>
      </section>

      <section className="px-4 py-14 sm:px-6 sm:py-16 lg:px-8"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.38fr_.62fr]"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#287f78] dark:text-[#65d4c6]">Eligibility rule builder</p><h2 className="mt-3 font-heading text-3xl font-semibold leading-tight sm:text-4xl">Write the rule before learners enrol.</h2><p className="mt-5 text-sm leading-7 text-slate-600 dark:text-slate-300">A learner should know what completion means. Combine only the signals that matter for the program—not every metric available in the software.</p><div className="mt-6 border-l-2 border-[#b59659] pl-5"><p className="font-heading text-lg font-semibold">Example rule</p><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">Issue the achievement certificate after all required modules, 75% live attendance, a 70% exam score, and faculty approval of the final project.</p></div></div><div className="space-y-3">{ruleParts.map(([Icon, title, detail, threshold], index) => <article key={title} className="grid gap-4 rounded-xl border border-[#10233f]/10 bg-white/65 p-4 sm:grid-cols-[3rem_.7fr_1fr] sm:items-center dark:border-white/10 dark:bg-white/[.035]"><div className="grid size-10 place-items-center rounded-full bg-[#d8eee9] text-[#287f78] dark:bg-emerald-300/10 dark:text-emerald-200"><Icon className="size-5" /></div><div><p className="text-[.58rem] font-semibold uppercase tracking-[.13em] text-slate-400">Rule 0{index + 1}</p><h3 className="mt-1 font-heading text-base font-semibold">{title}</h3><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">{detail}</p></div><div className="rounded-lg border border-[#10233f]/10 bg-[#f5f1e8] px-3 py-2 text-xs font-semibold dark:border-white/10 dark:bg-white/5">{threshold}</div></article>)}</div></div></section>

      <section className="bg-[#102b4d] px-4 py-14 text-white sm:px-6 sm:py-16 lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-[.35fr_.65fr]"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#76ddcf]">Credential lifecycle</p><h2 className="mt-3 font-heading text-3xl font-semibold leading-tight sm:text-4xl">Issuing the PDF is only one step.</h2><p className="mt-5 text-sm leading-7 text-blue-100">Keep learner identity, eligibility evidence, certificate data, status, corrections, and verification connected to one controlled record.</p></div><div className="grid gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-3">{[
          [Target, "Define", "Credential title, wording, evidence, threshold, and authority."], [UserRoundCheck, "Confirm", "Learner identity and display name before generation."], [FileBadge2, "Issue", "Create the branded credential with ID, date, and signatory."], [Fingerprint, "Record", "Store recipient, rule result, version, and issuing actor."], [QrCode, "Verify", "Let an authorised viewer confirm current credential status."], [RotateCcw, "Correct or revoke", "Preserve audit history when facts or validity change."],
        ].map(([Icon, title, text], index) => { const FlowIcon = Icon as typeof Target; return <article key={String(title)} className="bg-[#123355] p-4"><div className="flex items-center justify-between"><FlowIcon className="size-5 text-[#76ddcf]" /><span className="font-mono text-[.58rem] text-blue-200/60">0{index + 1}</span></div><h3 className="mt-5 font-heading text-lg font-semibold">{String(title)}</h3><p className="mt-2 text-xs leading-5 text-blue-100/80">{String(text)}</p></article>; })}</div></div></div></section>

      <section className="px-4 py-14 sm:px-6 sm:py-16 lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-7 lg:grid-cols-[.38fr_.62fr] lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#287f78] dark:text-[#65d4c6]">Certificate anatomy</p><h2 className="mt-3 font-heading text-3xl font-semibold leading-tight">Make every field earn its place.</h2></div><p className="max-w-3xl text-sm leading-7 text-slate-600 dark:text-slate-300">A certificate should be easy to read, difficult to misunderstand, and possible to trace. Decorative detail comes after factual clarity.</p></div><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[
          [GraduationCap, "Recipient", "Verified learner name and, when needed, a learner identifier."], [PenLine, "Claim", "Credential type, program title, and precise completion wording."], [KeyRound, "Authority", "Academy identity, authorised signatory, and issue date."], [ShieldCheck, "Traceability", "Unique ID, current status, version, and verification path."],
        ].map(([Icon, title, text], index) => { const AnatomyIcon = Icon as typeof GraduationCap; return <article key={String(title)} className="rounded-2xl border border-[#10233f]/10 bg-white/65 p-5 dark:border-white/10 dark:bg-white/[.04]"><div className="flex items-center justify-between"><AnatomyIcon className="size-5 text-[#287f78] dark:text-[#65d4c6]" /><span className="font-mono text-[.58rem] text-slate-400">0{index + 1}</span></div><h3 className="mt-6 font-heading text-lg font-semibold">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{String(text)}</p></article>; })}</div></div></section>

      <section className="border-y border-[#10233f]/10 bg-[#e4efec] px-4 py-12 sm:px-6 lg:px-8 dark:border-white/10 dark:bg-[#0a1c2e]"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[.34fr_.66fr]"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#287f78] dark:text-[#65d4c6]">Pilot checklist</p><h2 className="mt-3 font-heading text-3xl font-semibold leading-tight">Test one credential from eligibility to verification.</h2><p className="mt-4 text-sm leading-7 text-slate-600 dark:text-slate-300">Use separate admin and learner accounts. Test a passing learner, an ineligible learner, a name correction, and a revoked credential.</p></div><div className="grid gap-px overflow-hidden rounded-2xl border border-[#10233f]/10 bg-[#10233f]/10 sm:grid-cols-2 dark:border-white/10 dark:bg-white/10">{[
          "Credential title matches the evidence actually collected", "Eligibility rule is visible before enrolment", "Learner name and course details are checked", "Dates, signatory, logo, and wording print clearly", "Unique ID is never reused across learners", "Failed and incomplete learners cannot issue early", "Correction and revocation leave an audit trail", "Mobile download, print, sharing, and verification are tested",
        ].map((item, index) => <div key={item} className="flex gap-3 bg-[#f8fbf9] p-4 text-sm leading-6 dark:bg-[#0d2238]"><span className="grid size-6 shrink-0 place-items-center rounded-full bg-[#287f78] text-[.62rem] font-bold text-white">{index + 1}</span>{item}</div>)}</div></div></section>

      <section className="px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-6 border-b border-[#10233f]/10 pb-12 dark:border-white/10 lg:grid-cols-[.28fr_.72fr] lg:items-center"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#287f78] dark:text-[#65d4c6]">Credential workbench</p><h2 className="mt-3 font-heading text-3xl font-semibold leading-tight">Connect evidence, output, and document control.</h2></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[
        ["Certificate generator", "/tools/certificate-generator", "Prototype wording, identity fields, and visual hierarchy."], ["Report card generator", "/tools/report-card-generator", "Create a supporting academic performance record."], ["Grade calculator", "/tools/grade-calculator", "Check the grade behind an eligibility decision."], ["Watermark certificate PDF", "/pdf-tools/add-pdf-watermark", "Add controlled branding or status text to an exported PDF."], ["Protect certificate PDF", "/pdf-tools/protect-pdf", "Add password protection when a document needs controlled access."], ["Exams and assignments", "/features/exams-assignments-certificates", "Explore assessment, submission, and certificate workflows."],
      ].map(([title, href, text]) => <Link key={title} href={href} className="group rounded-xl border border-[#10233f]/10 bg-white/65 p-4 dark:border-white/10 dark:bg-white/[.04]"><h3 className="font-heading text-base font-semibold">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-500 dark:text-slate-400">{text}</p><span className="mt-4 inline-flex items-center gap-2 text-xs font-semibold text-[#287f78] dark:text-[#65d4c6]">Open next <ArrowRight className="size-3.5 transition group-hover:translate-x-1" /></span></Link>)}</div></div></section>

      <section className="px-4 pb-14 sm:px-6 sm:pb-16 lg:px-8"><div className="mx-auto grid max-w-7xl gap-9 lg:grid-cols-[.32fr_.68fr]"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#287f78] dark:text-[#65d4c6]">Certificate questions</p><h2 className="mt-3 font-heading text-3xl font-semibold leading-tight">Promise only what the credential can prove.</h2><div className="mt-6 rounded-2xl bg-[#102b4d] p-5 text-white"><MessageCircleMore className="size-5 text-[#76ddcf]" /><p className="mt-4 font-heading text-lg font-semibold">Bring one real program.</p><p className="mt-2 text-sm leading-6 text-blue-100">We can map its eligibility, wording, issuance, correction, and verification flow.</p><ProductTourTrigger label="Review the credential flow" variant="solid" size="sm" className="mt-5 w-full justify-center" /></div></div><div className="border-t border-[#10233f]/10 dark:border-white/10">{faqs.map(([question, answer], index) => <details key={question} open={index === 0} className="group border-b border-[#10233f]/10 py-5 dark:border-white/10"><summary className="flex cursor-pointer list-none items-start justify-between gap-5"><span className="flex gap-3"><span className="mt-1 font-mono text-[.62rem] text-[#287f78]/60">0{index + 1}</span><span className="font-heading text-base font-semibold leading-7 sm:text-lg">{question}</span></span><span className="grid size-8 shrink-0 place-items-center rounded-full border border-[#10233f]/15 text-[#287f78] transition group-open:rotate-45 dark:border-white/15 dark:text-[#65d4c6]">+</span></summary><p className="mt-3 max-w-3xl pl-10 pr-10 text-sm leading-7 text-slate-600 dark:text-slate-300">{answer}</p></details>)}</div></div></section>

      <section className="px-4 pb-14 sm:px-6 sm:pb-16 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-6 rounded-[1.5rem] bg-[linear-gradient(110deg,#153b68,#28716f_58%,#9d7735)] p-6 text-white sm:p-8 lg:flex-row lg:items-center lg:justify-between"><div><div className="inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[.18em] text-emerald-100"><Sparkles className="size-4" />Ready to define meaningful completion?</div><h2 className="mt-3 max-w-3xl font-heading text-3xl font-semibold leading-tight">Build the rule first. Design the certificate second.</h2></div><div className="flex shrink-0 flex-col gap-3 sm:flex-row"><ProductTourTrigger label="Plan the KASA workflow" variant="solid" size="sm" className="justify-center" /><Link href="/tools/certificate-generator" className="inline-flex h-10 items-center justify-center gap-2 rounded-full border border-white/20 bg-white/10 px-5 text-sm font-semibold">Create a sample <ArrowRight className="size-4" /></Link></div></div></section>
    </main>
  </>;
}
