import Link from "next/link";
import {
  ArrowRight,
  BadgeIndianRupee,
  BarChart3,
  Calculator,
  Check,
  Clock3,
  Coins,
  FileCheck2,
  Layers3,
  MessageCircleMore,
  PackageCheck,
  ReceiptText,
  ShieldCheck,
  Sparkles,
  Target,
  TrendingUp,
  UsersRound,
  WalletCards,
} from "lucide-react";
import { ProductTourTrigger } from "@/components/site/product-tour-trigger";
import { BreadcrumbStructuredData, FaqStructuredData, WebPageStructuredData } from "@/components/site/structured-data";
import type { PageSummary } from "@/lib/site-content";

const faqs: Array<[string, string]> = [
  ["How should I decide the price of an online course?", "Start with the learner and outcome, then examine delivery format, faculty involvement, support, assessment, proof, duration, market alternatives, acquisition cost, payment charges, taxes, refunds, and the minimum margin needed to deliver responsibly. Price is a business decision, not a word-count or video-hours formula."],
  ["Should a live course cost more than a recorded course?", "Often, but not automatically. Live teaching, feedback, accountability, limited seats, and faculty access increase delivery depth and cost. A highly specialised recorded program with valuable tools and outcomes may still justify a higher price than a basic live webinar."],
  ["Is competitor pricing the best benchmark?", "Competitor pricing is context, not the answer. Two programs with similar titles may differ in audience, outcome, trust, support, duration, faculty, proof, refunds, and acquisition model. Compare the complete offer and delivery responsibility, not only the displayed number."],
  ["How much discount should I offer on a course?", "There is no universal percentage. Set a floor based on variable cost, tax and payment impact, support obligations, refund risk, acquisition cost, and required contribution. Use a clear reason, audience, duration, and redemption limit instead of permanent fake urgency."],
  ["Should I offer instalments?", "Instalments can improve affordability for higher-priced programs, but define due dates, access rules, payment failure handling, refunds, collection ownership, and whether the total instalment price differs from upfront payment. Make the terms visible before purchase."],
  ["When should I increase the course price?", "Review price when the outcome, curriculum, support, faculty access, proof, demand, completion experience, costs, or positioning materially changes. Existing learner feedback and conversion data can inform the decision, but no metric guarantees that a higher price will perform better."],
];

const pricingInputs = [
  [Target, "Outcome", "Urgency, specificity, and value of the learner result"],
  [Layers3, "Delivery", "Recorded, live, hybrid, cohort, or reviewed work"],
  [UsersRound, "Support", "Faculty time, feedback, doubts, and community"],
  [FileCheck2, "Proof", "Assessment, project, review, and certificate depth"],
  [Coins, "Economics", "Costs, acquisition, tax, refunds, and margin"],
] as const;

const deliveryModels = [
  ["Self-paced", "Scalable access", "Production, hosting, learner support, updates", "Use when learners can progress independently"],
  ["Live cohort", "Time and accountability", "Faculty hours, capacity, rescheduling, operations", "Use when interaction materially improves the result"],
  ["Hybrid", "Flexibility + guidance", "Recorded library plus scheduled teaching and support", "Use when preparation and application need different formats"],
  ["Reviewed program", "Evidence and feedback", "Evaluation, rubrics, projects, corrections, proof", "Use when quality depends on human judgement"],
] as const;

export function OnlineCoursePricingGuidePage({ page }: { page: PageSummary }) {
  return <>
    <BreadcrumbStructuredData items={[{ name: "Home", href: "/" }, { name: "Resources", href: "/resources" }, { name: page.title, href: `/resources/${page.slug}` }]} />
    <WebPageStructuredData name={page.title} description={page.description} href={`/resources/${page.slug}`} pageType="Article" />
    <FaqStructuredData faqs={faqs} />

    <main className="overflow-hidden bg-[#f5f7f4] text-[#101b2e] dark:bg-[#071225] dark:text-white">
      <section className="relative px-4 pb-14 pt-32 sm:px-6 sm:pt-36 lg:px-8">
        <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_10%_20%,rgba(66,153,141,.15),transparent_27rem),radial-gradient(circle_at_88%_18%,rgba(51,106,188,.13),transparent_31rem)]" />
        <div className="relative mx-auto max-w-7xl">
          <nav aria-label="Breadcrumb" className="flex items-center gap-2 text-xs font-medium text-slate-500 dark:text-slate-400"><Link href="/" className="hover:text-primary">Home</Link><span>/</span><Link href="/resources" className="hover:text-primary">Resources</Link><span>/</span><span className="text-[#101b2e] dark:text-white">Course pricing guide</span></nav>
          <div className="mt-8 grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center xl:gap-16">
            <div><div className="inline-flex items-center gap-2 rounded-full border border-[#287f78]/20 bg-[#d9efea] px-3 py-1.5 text-[.68rem] font-semibold uppercase tracking-[.2em] text-[#246c65] dark:border-emerald-200/15 dark:bg-emerald-200/10 dark:text-emerald-200"><BadgeIndianRupee className="size-3.5" />Course pricing field guide</div><h1 className="mt-5 max-w-xl font-heading text-[2.4rem] font-semibold leading-[1.04] tracking-[-.045em] sm:text-5xl lg:text-[3.45rem]">Price the <span className="text-[#287f78] dark:text-[#65d4c6]">whole learning promise</span>—not the number of videos.</h1><p className="mt-6 max-w-xl text-base leading-8 text-slate-600 dark:text-slate-300">Build a defensible course price from learner outcome, delivery depth, support load, proof, costs, and commercial risk—then test the offer with real buyers.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link href="/tools/course-pricing-calculator" className="inline-flex h-10 items-center justify-center gap-2 rounded-full bg-[linear-gradient(100deg,#173e7a,#1b9fd0)] px-5 text-sm font-semibold text-white shadow-lg shadow-blue-950/15"><Calculator className="size-4" />Calculate a starting price</Link><Link href="/pricing" className="inline-flex h-10 items-center justify-center gap-2 rounded-full border border-[#101b2e]/15 bg-white/65 px-5 text-sm font-semibold dark:border-white/15 dark:bg-white/5">View KASA pricing <ArrowRight className="size-4" /></Link></div></div>

            <div className="rounded-[1.7rem] border border-[#101b2e]/10 bg-[#0e2648] p-3 text-white shadow-[0_35px_90px_-48px_rgba(14,38,72,.8)] dark:border-white/10"><div className="flex items-center justify-between px-2 pb-3"><span className="text-[.62rem] font-semibold uppercase tracking-[.17em] text-emerald-200">Pricing worksheet · illustrative</span><span className="rounded-full bg-white/10 px-2.5 py-1 text-[.6rem] text-blue-100">Hybrid cohort</span></div><div className="grid gap-px overflow-hidden rounded-xl bg-white/10 sm:grid-cols-[.62fr_.38fr]"><div className="bg-[#f7faf8] p-4 text-[#101b2e] sm:p-5"><p className="text-[.6rem] font-semibold uppercase tracking-[.15em] text-slate-400">Offer assumptions</p><div className="mt-4 space-y-3">{[["Learners", "30"], ["Program length", "8 weeks"], ["Faculty + support", "₹72,000"], ["Platform, tools, ops", "₹24,000"], ["Acquisition allowance", "₹45,000"]].map(([label, value]) => <div key={label} className="flex items-center justify-between border-b border-slate-200 pb-2 text-xs"><span className="text-slate-500">{label}</span><strong>{value}</strong></div>)}</div><p className="mt-4 text-[.58rem] leading-4 text-slate-400">Example numbers only. Taxes, payment fees, refunds, utilisation, and actual costs vary.</p></div><div className="bg-[#12365f] p-4 sm:p-5"><p className="text-[.6rem] font-semibold uppercase tracking-[.15em] text-blue-200">Scenario output</p><div className="mt-5"><p className="text-[.62rem] text-blue-200">Displayed price</p><p className="mt-1 font-heading text-3xl font-semibold">₹7,500</p><p className="mt-1 text-[.6rem] text-blue-200">per learner</p></div><div className="mt-6 space-y-3">{[["Revenue at 30 seats", "₹2,25,000"], ["Modelled direct spend", "₹1,41,000"], ["Contribution before other overhead", "₹84,000"]].map(([label, value]) => <div key={label}><p className="text-[.58rem] text-blue-200">{label}</p><p className="mt-0.5 text-sm font-semibold">{value}</p></div>)}</div></div></div><div className="flex items-center gap-2 px-3 py-2.5 text-[.6rem] text-blue-100"><ShieldCheck className="size-3.5 text-emerald-300" />Model the full cost; this illustration is not a revenue or profit promise.</div></div>
          </div>
        </div>
      </section>

      <section className="border-y border-[#101b2e]/10 bg-white px-4 py-12 sm:px-6 lg:px-8 dark:border-white/10 dark:bg-[#09182d]"><div className="mx-auto max-w-7xl"><div className="grid gap-6 lg:grid-cols-[.33fr_.67fr] lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#287f78] dark:text-[#65d4c6]">Five pricing inputs</p><h2 className="mt-3 font-heading text-3xl font-semibold leading-tight">Start with the offer—not a competitor’s number.</h2></div><p className="max-w-3xl text-sm leading-7 text-slate-600 dark:text-slate-300">A sustainable price sits at the intersection of learner value, delivery responsibility, market context, and viable economics. No single input decides it alone.</p></div><div className="mt-8 grid overflow-hidden rounded-2xl border border-[#101b2e]/10 sm:grid-cols-2 lg:grid-cols-5 dark:border-white/10">{pricingInputs.map(([Icon, title, text], index) => <article key={title} className="border-b border-r border-[#101b2e]/10 bg-[#fafbf8] p-4 dark:border-white/10 dark:bg-white/[.035]"><span className="font-mono text-[.58rem] text-[#287f78]/50">0{index + 1}</span><Icon className="mt-6 size-5 text-[#287f78] dark:text-[#65d4c6]" /><h3 className="mt-4 font-heading text-base font-semibold">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-500 dark:text-slate-400">{text}</p></article>)}</div></div></section>

      <section className="px-4 py-14 sm:px-6 sm:py-16 lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-7 lg:grid-cols-[.38fr_.62fr] lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#287f78] dark:text-[#65d4c6]">Delivery changes economics</p><h2 className="mt-3 font-heading text-3xl font-semibold leading-tight sm:text-4xl">Price the responsibility you accept.</h2></div><p className="max-w-3xl text-sm leading-7 text-slate-600 dark:text-slate-300">Two courses with the same topic and duration can require completely different faculty time, support, capacity, technology, and quality control.</p></div><div className="mt-8 overflow-hidden border-y border-[#101b2e]/15 dark:border-white/15">{deliveryModels.map(([model, value, cost, fit], index) => <article key={model} className="grid gap-3 border-b border-[#101b2e]/10 px-1 py-5 last:border-b-0 md:grid-cols-[3rem_.18fr_.25fr_.3fr_.27fr] md:items-center dark:border-white/10"><span className="font-mono text-[.6rem] text-[#287f78]/55">0{index + 1}</span><h3 className="font-heading text-lg font-semibold">{model}</h3><div><p className="text-[.58rem] font-semibold uppercase tracking-[.12em] text-slate-400">Buyer value</p><p className="mt-1 text-xs leading-5">{value}</p></div><div><p className="text-[.58rem] font-semibold uppercase tracking-[.12em] text-slate-400">Delivery load</p><p className="mt-1 text-xs leading-5">{cost}</p></div><div><p className="text-[.58rem] font-semibold uppercase tracking-[.12em] text-slate-400">Best fit</p><p className="mt-1 text-xs leading-5">{fit}</p></div></article>)}</div></div></section>

      <section className="bg-[#102c50] px-4 py-14 text-white sm:px-6 sm:py-16 lg:px-8"><div className="mx-auto grid max-w-7xl gap-9 lg:grid-cols-[.35fr_.65fr]"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#76ddcf]">Count the quiet costs</p><h2 className="mt-3 font-heading text-3xl font-semibold leading-tight sm:text-4xl">Revenue is not the amount left to keep.</h2><p className="mt-5 text-sm leading-7 text-blue-100">Separate one-time production, recurring overhead, per-learner delivery, and acquisition. Then add room for uncertainty rather than assuming every seat fills.</p></div><div className="grid gap-3 sm:grid-cols-2">{[
        [PackageCheck, "Build once", "Curriculum, recording, editing, design, setup, landing page, migration"], [Clock3, "Deliver repeatedly", "Faculty, mentors, grading, live sessions, doubt support, operations"], [WalletCards, "Sell and collect", "Marketing, sales time, coupons, gateway fees, tax handling, failed payments"], [ShieldCheck, "Protect the promise", "Refunds, replacements, moderation, updates, learner support, contingencies"],
      ].map(([Icon, title, text], index) => { const CostIcon = Icon as typeof PackageCheck; return <article key={String(title)} className="rounded-xl border border-white/10 bg-white/[.055] p-4"><div className="flex items-center justify-between"><CostIcon className="size-5 text-[#76ddcf]" /><span className="font-mono text-[.58rem] text-blue-200/60">0{index + 1}</span></div><h3 className="mt-5 font-heading text-lg font-semibold">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-blue-100/85">{String(text)}</p></article>; })}</div></div></section>

      <section className="px-4 py-14 sm:px-6 sm:py-16 lg:px-8"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.4fr_.6fr]"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#287f78] dark:text-[#65d4c6]">Offer ladder</p><h2 className="mt-3 font-heading text-3xl font-semibold leading-tight sm:text-4xl">Change the service—not only the price tag.</h2><p className="mt-5 text-sm leading-7 text-slate-600 dark:text-slate-300">Useful tiers serve different needs. Avoid inventing a “premium” tier that contains the same experience with a crossed-out number.</p><div className="mt-6 rounded-xl border border-[#287f78]/15 bg-[#e4f1ee] p-4 dark:border-emerald-200/10 dark:bg-emerald-200/5"><TrendingUp className="size-5 text-[#287f78] dark:text-[#65d4c6]" /><p className="mt-3 text-sm font-semibold">Keep the core promise intact.</p><p className="mt-2 text-xs leading-5 text-slate-600 dark:text-slate-300">Higher tiers may add speed, access, review, accountability, or convenience—not hide essential delivery behind surprise fees.</p></div></div><div className="grid gap-3 sm:grid-cols-3">{[
        ["Learn", "Independent", "Recorded curriculum", ["Lessons and resources", "Defined support route", "Completion tracking"]], ["Apply", "Guided", "Cohort + feedback", ["Everything in Learn", "Live application sessions", "Assignment feedback"]], ["Accelerate", "Reviewed", "High-touch outcome", ["Everything in Apply", "Project review", "Smaller group or 1:1 access"]],
      ].map(([title, label, model, features], index) => <article key={String(title)} className={`rounded-2xl border p-5 ${index === 1 ? "border-[#287f78] bg-[#e8f4f1] shadow-lg shadow-emerald-950/5 dark:bg-emerald-200/[.06]" : "border-[#101b2e]/10 bg-white/65 dark:border-white/10 dark:bg-white/[.035]"}`}><span className="text-[.58rem] font-semibold uppercase tracking-[.14em] text-[#287f78] dark:text-[#65d4c6]">{String(label)}</span><h3 className="mt-4 font-heading text-2xl font-semibold">{String(title)}</h3><p className="mt-2 text-sm text-slate-500 dark:text-slate-400">{String(model)}</p><div className="mt-6 space-y-3">{(features as string[]).map(feature => <div key={feature} className="flex gap-2 text-xs leading-5"><Check className="mt-0.5 size-3.5 shrink-0 text-[#287f78] dark:text-[#65d4c6]" />{feature}</div>)}</div></article>)}</div></div></section>

      <section className="border-y border-[#101b2e]/10 bg-[#eaf0f7] px-4 py-14 sm:px-6 lg:px-8 dark:border-white/10 dark:bg-[#0a1c33]"><div className="mx-auto grid max-w-7xl gap-9 lg:grid-cols-[.34fr_.66fr]"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-primary dark:text-[#65d4c6]">Discount guardrails</p><h2 className="mt-3 font-heading text-3xl font-semibold leading-tight">A coupon needs a job, a limit, and an owner.</h2><p className="mt-4 text-sm leading-7 text-slate-600 dark:text-slate-300">Discounts can support a launch, partner, scholarship, early commitment, or recovery campaign. Permanent urgency trains buyers to wait and makes the displayed price less credible.</p></div><div className="grid gap-px overflow-hidden rounded-2xl border border-[#101b2e]/10 bg-[#101b2e]/10 sm:grid-cols-2 dark:border-white/10 dark:bg-white/10">{[
        ["Reason", "Why does this offer exist, and who is eligible?"], ["Floor", "What minimum collected amount keeps delivery responsible?"], ["Window", "When does it start and end without fake countdowns?"], ["Limit", "How many redemptions, seats, or uses are allowed?"], ["Stacking", "Can it combine with instalments, scholarships, or partner codes?"], ["Measurement", "Did it improve qualified enrolment, collection, and completion?"],
      ].map(([title, text], index) => <div key={title} className="bg-[#f8fafc] p-4 dark:bg-[#0d223b]"><div className="flex items-center gap-3"><span className="grid size-6 place-items-center rounded-full bg-[#214f86] text-[.6rem] font-bold text-white">{index + 1}</span><h3 className="font-heading text-base font-semibold">{title}</h3></div><p className="mt-3 pl-9 text-xs leading-5 text-slate-500 dark:text-slate-400">{text}</p></div>)}</div></div></section>

      <section className="px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-6 border-b border-[#101b2e]/10 pb-12 dark:border-white/10 lg:grid-cols-[.28fr_.72fr] lg:items-center"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#287f78] dark:text-[#65d4c6]">Model before launch</p><h2 className="mt-3 font-heading text-3xl font-semibold leading-tight">Use the numbers as questions—not promises.</h2></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[
        [Calculator, "Course pricing calculator", "/tools/course-pricing-calculator", "Model price, costs, margin, and enrolment targets."], [BarChart3, "Profit calculator", "/tools/profit-calculator", "Compare revenue, operating spend, and contribution."], [UsersRound, "Batch capacity calculator", "/tools/batch-capacity-calculator", "Test seat limits against faculty and delivery load."], [ReceiptText, "Fee receipt generator", "/tools/fee-receipt-generator", "Plan the information needed after manual collection."],
      ].map(([Icon, title, href, text]) => { const ToolIcon = Icon as typeof Calculator; return <Link key={String(title)} href={String(href)} className="group rounded-xl border border-[#101b2e]/10 bg-white/65 p-4 dark:border-white/10 dark:bg-white/[.04]"><ToolIcon className="size-5 text-[#287f78] dark:text-[#65d4c6]" /><h3 className="mt-4 font-heading text-base font-semibold">{String(title)}</h3><p className="mt-2 text-xs leading-5 text-slate-500 dark:text-slate-400">{String(text)}</p><span className="mt-4 inline-flex items-center gap-2 text-xs font-semibold text-[#287f78] dark:text-[#65d4c6]">Open tool <ArrowRight className="size-3.5 transition group-hover:translate-x-1" /></span></Link>; })}</div></div></section>

      <section className="px-4 pb-14 sm:px-6 sm:pb-16 lg:px-8"><div className="mx-auto grid max-w-7xl gap-9 lg:grid-cols-[.32fr_.68fr]"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#287f78] dark:text-[#65d4c6]">Pricing questions</p><h2 className="mt-3 font-heading text-3xl font-semibold leading-tight">Set the boundaries before publishing the number.</h2><div className="mt-6 rounded-2xl bg-[#102c50] p-5 text-white"><MessageCircleMore className="size-5 text-[#76ddcf]" /><p className="mt-4 font-heading text-lg font-semibold">Bring one real offer.</p><p className="mt-2 text-sm leading-6 text-blue-100">We can map its buyer, delivery, costs, tiers, payment rules, and learner access.</p><ProductTourTrigger label="Review the course workflow" variant="solid" size="sm" className="mt-5 w-full justify-center" /></div></div><div className="border-t border-[#101b2e]/10 dark:border-white/10">{faqs.map(([question, answer], index) => <details key={question} open={index === 0} className="group border-b border-[#101b2e]/10 py-5 dark:border-white/10"><summary className="flex cursor-pointer list-none items-start justify-between gap-5"><span className="flex gap-3"><span className="mt-1 font-mono text-[.62rem] text-[#287f78]/60">0{index + 1}</span><span className="font-heading text-base font-semibold leading-7 sm:text-lg">{question}</span></span><span className="grid size-8 shrink-0 place-items-center rounded-full border border-[#101b2e]/15 text-[#287f78] transition group-open:rotate-45 dark:border-white/15 dark:text-[#65d4c6]">+</span></summary><p className="mt-3 max-w-3xl pl-10 pr-10 text-sm leading-7 text-slate-600 dark:text-slate-300">{answer}</p></details>)}</div></div></section>

      <section className="px-4 pb-14 sm:px-6 sm:pb-16 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-6 rounded-[1.5rem] bg-[linear-gradient(110deg,#173f76,#1a6e8c_56%,#258378)] p-6 text-white sm:p-8 lg:flex-row lg:items-center lg:justify-between"><div><div className="inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[.18em] text-emerald-100"><Sparkles className="size-4" />Ready to test a sustainable offer?</div><h2 className="mt-3 max-w-3xl font-heading text-3xl font-semibold leading-tight">Model one course, one cohort, and one realistic sales scenario.</h2></div><div className="flex shrink-0 flex-col gap-3 sm:flex-row"><Link href="/tools/course-pricing-calculator" className="inline-flex h-10 items-center justify-center gap-2 rounded-full bg-white px-5 text-sm font-semibold text-[#173f76]">Open pricing calculator <ArrowRight className="size-4" /></Link><Link href="/resources/sell-recorded-courses-online" className="inline-flex h-10 items-center justify-center gap-2 rounded-full border border-white/20 bg-white/10 px-5 text-sm font-semibold">Plan delivery <ArrowRight className="size-4" /></Link></div></div></section>
    </main>
  </>;
}
