import Link from "next/link";
import { ArrowRight, BadgeIndianRupee, BookOpenCheck, Check, CircleDot, Clock3, FileBadge2, FileText, Layers3, LockKeyhole, MessageCircleMore, PlayCircle, ShieldCheck, Sparkles, Target } from "lucide-react";
import { ProductTourTrigger } from "@/components/site/product-tour-trigger";
import { BreadcrumbStructuredData, FaqStructuredData, WebPageStructuredData } from "@/components/site/structured-data";
import type { PageSummary } from "@/lib/site-content";

const faqs: Array<[string, string]> = [
  ["What do I need before I can sell a recorded course online?", "You need a clearly defined learner, useful outcome, structured curriculum, essential videos and resources, pricing, policies, support ownership, a sales page, payment setup, and a tested learner-access flow. A large video library is not a substitute for this complete journey."],
  ["Should I record the entire course before launching?", "Not always. You should have enough complete material to deliver the promise reliably, but a controlled pilot can reveal where learners need different examples, resources, or support before you polish every optional lesson."],
  ["How should payment and course access connect?", "A successful payment should create or identify the learner, record the order, apply the correct program and access rule, and show a clear next step. Failure, duplicate payment, refund, expiry, and manual-payment scenarios also need an owner and tested response."],
  ["Do recorded courses need live support?", "The content may be self-paced, but learners still need a defined support path for access issues, academic doubts, feedback, and accountability. Support can be asynchronous, scheduled, community-based, or offered as a higher-value layer."],
  ["Should every recorded course include a certificate?", "No. A certificate makes sense when it represents a meaningful completion rule such as required lessons, an assessment, reviewed work, or manual approval. Issuing one only for opening videos weakens its value."],
  ["What affects KASA pricing for a recorded-course academy?", "The edition, learners, courses, team roles, storage and playback usage, migration, payment and email setup, domain requirements, integrations, and rollout support can affect scope. Confirm these against one real course before purchase."],
];

const launchFlow = [
  [Target, "Position", "One learner, urgent problem, credible result"],
  [BookOpenCheck, "Structure", "Modules, lessons, practice, and milestones"],
  [PlayCircle, "Produce", "Clear video, useful resources, accessible delivery"],
  [BadgeIndianRupee, "Sell", "Program page, price, policy, and checkout"],
  [LockKeyhole, "Deliver", "Account, access, progress, and communication"],
  [FileBadge2, "Prove", "Completion rule, result, and certificate"],
] as const;

export function SellRecordedCoursesOnlinePage({ page }: { page: PageSummary }) {
  return <>
    <BreadcrumbStructuredData items={[{ name: "Home", href: "/" }, { name: "Resources", href: "/resources" }, { name: page.title, href: `/resources/${page.slug}` }]} />
    <WebPageStructuredData name={page.title} description={page.description} href={`/resources/${page.slug}`} pageType="Article" />
    <FaqStructuredData faqs={faqs} />

    <main className="overflow-hidden bg-[#f8f7f2] text-slate-950 dark:bg-[#061126] dark:text-white">
      <section className="relative px-4 pb-14 pt-32 sm:px-6 sm:pb-16 sm:pt-36 lg:px-8"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_12%_18%,rgba(72,140,255,.16),transparent_28rem),radial-gradient(circle_at_88%_24%,rgba(55,204,153,.13),transparent_30rem)]" /><div className="relative mx-auto max-w-7xl"><nav aria-label="Breadcrumb" className="flex items-center gap-2 text-xs font-medium text-slate-500 dark:text-slate-400"><Link href="/" className="hover:text-primary">Home</Link><span>/</span><Link href="/resources" className="hover:text-primary">Resources</Link><span>/</span><span className="text-slate-900 dark:text-white">Recorded courses</span></nav><div className="mt-8 grid gap-10 lg:grid-cols-[.78fr_1.22fr] lg:items-center xl:gap-16"><div><div className="inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[.22em] text-primary dark:text-emerald-300"><PlayCircle className="size-4" />Recorded-course field guide</div><h1 className="mt-5 max-w-xl font-heading text-[2.4rem] font-semibold leading-[1.05] tracking-[-.04em] sm:text-5xl lg:text-[3.35rem]">Sell a learning journey—not a folder of recorded videos.</h1><p className="mt-6 max-w-xl text-base leading-8 text-slate-600 dark:text-slate-300">Build the offer, curriculum, sales page, checkout, learner access, support, progress, and completion proof as one branded course experience.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><ProductTourTrigger label="Map my recorded course" variant="solid" size="sm" className="justify-center" /><Link href="/tools/course-pricing-calculator" className="inline-flex h-10 items-center justify-center gap-2 rounded-full border border-primary/20 bg-white/70 px-5 text-sm font-semibold text-primary dark:border-white/15 dark:bg-white/5 dark:text-white">Price the course <ArrowRight className="size-4" /></Link></div></div>
        <div className="overflow-hidden rounded-[1.6rem] border border-blue-950/10 bg-[#081e3d] p-3 text-white shadow-[0_35px_100px_-50px_rgba(8,30,61,.75)] dark:border-white/10"><div className="flex items-center justify-between px-2 pb-3"><span className="text-[.62rem] font-semibold uppercase tracking-[.18em] text-emerald-300">Learner view / course player</span><span className="flex items-center gap-2 text-[.62rem] text-blue-200"><CircleDot className="size-3 text-emerald-300" />Access active</span></div><div className="grid overflow-hidden rounded-xl border border-white/10 bg-[#0b2852] sm:grid-cols-[.72fr_.28fr]"><div className="relative aspect-video overflow-hidden bg-black"><video autoPlay muted loop playsInline preload="metadata" className="size-full object-cover" aria-label="KASA self-paced course player preview"><source src="/feature-self-learning.mp4" type="video/mp4" /></video><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/80 to-transparent px-4 pb-3 pt-10"><p className="text-xs font-semibold">Module 02 · Build the core skill</p><div className="mt-2 h-1 overflow-hidden rounded-full bg-white/20"><div className="h-full w-[62%] rounded-full bg-emerald-300" /></div></div></div><aside className="p-3"><p className="text-[.6rem] font-semibold uppercase tracking-[.16em] text-blue-200">Course path</p>{[["01", "Welcome and outcome", true], ["02", "Core framework", true], ["03", "Guided practice", false], ["04", "Final application", false]].map(([number, title, active]) => <div key={String(number)} className={`mt-2 rounded-lg border p-2.5 ${active ? "border-emerald-300/25 bg-emerald-300/10" : "border-white/10 bg-white/[.03]"}`}><span className="text-[.55rem] text-blue-200">{number}</span><p className="mt-1 text-[.68rem] font-semibold leading-4">{String(title)}</p></div>)}</aside></div><div className="grid gap-px bg-white/10 sm:grid-cols-3">{[[Clock3, "14 lessons", "2h 48m"], [FileText, "6 resources", "Ready to download"], [ShieldCheck, "Completion", "Assessment required"]].map(([Icon, title, value]) => { const ItemIcon = Icon as typeof Layers3; return <div key={String(title)} className="bg-[#081e3d] p-3"><ItemIcon className="size-4 text-emerald-300" /><p className="mt-2 text-[.65rem] font-semibold">{String(title)}</p><p className="mt-0.5 text-[.6rem] text-blue-200">{String(value)}</p></div>; })}</div></div></div></div></section>

      <section className="border-y border-blue-950/8 bg-white px-4 py-14 sm:px-6 sm:py-16 lg:px-8 dark:border-white/8 dark:bg-[#08152a]"><div className="mx-auto max-w-7xl"><div className="grid gap-6 lg:grid-cols-[.35fr_.65fr] lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-primary dark:text-emerald-300">The complete product</p><h2 className="mt-4 font-heading text-3xl font-semibold leading-tight sm:text-4xl">Six systems turn expertise into a sellable course.</h2></div><p className="max-w-3xl text-sm leading-7 text-slate-600 dark:text-slate-300">Recording is only the production step. Buyers judge the promise and proof; learners experience access, structure, support, and progress.</p></div><div className="mt-9 grid gap-px overflow-hidden rounded-2xl border border-blue-950/10 bg-blue-950/10 sm:grid-cols-2 lg:grid-cols-6 dark:border-white/10 dark:bg-white/10">{launchFlow.map(([Icon, title, text], index) => <article key={title} className="relative bg-white p-4 dark:bg-[#0b1931]"><span className="font-mono text-[.6rem] text-primary/45">0{index + 1}</span><Icon className="mt-7 size-5 text-primary dark:text-emerald-300" /><h3 className="mt-4 font-heading text-base font-semibold">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-500 dark:text-slate-400">{text}</p>{index < launchFlow.length - 1 ? <ArrowRight className="absolute -right-3 top-1/2 z-10 hidden size-5 -translate-y-1/2 rounded-full bg-white text-emerald-500 lg:block dark:bg-[#0b1931]" /> : null}</article>)}</div></div></section>

      <section className="px-4 py-14 sm:px-6 sm:py-16 lg:px-8"><div className="mx-auto grid max-w-7xl gap-9 lg:grid-cols-[.42fr_.58fr]"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-primary dark:text-emerald-300">Package the transformation</p><h2 className="mt-4 font-heading text-3xl font-semibold leading-tight sm:text-4xl">Design backwards from what the learner should be able to do.</h2><p className="mt-4 text-sm leading-7 text-slate-600 dark:text-slate-300">A premium course feels intentional because every module earns its place. Start from evidence of the outcome, then plan practice, explanation, and orientation.</p><div className="mt-6 border-l-2 border-emerald-400 pl-5"><p className="font-heading text-lg font-semibold">Useful rule</p><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">One lesson should answer one learner question or enable one useful action. Split videos when the objective changes—not at an arbitrary duration.</p></div></div><div className="space-y-3">{[["04", "Evidence", "What will prove the promised outcome?", "A project, score, submission, demonstration, or reviewed application."], ["03", "Practice", "What must the learner try?", "Exercises, templates, decisions, examples, and feedback moments."], ["02", "Explanation", "What concepts and demonstrations enable the practice?", "Focused lessons with clear examples and supporting resources."], ["01", "Orientation", "What must be clear before learning begins?", "Outcome, prerequisites, roadmap, support route, and completion rule."]].map(([number, label, question, answer]) => <article key={number} className="grid gap-3 rounded-xl border border-blue-950/10 bg-white p-4 sm:grid-cols-[3.5rem_.7fr_1fr] sm:items-center dark:border-white/10 dark:bg-white/[.035]"><span className="font-heading text-2xl font-semibold text-primary/30 dark:text-emerald-300/30">{number}</span><div><p className="text-[.62rem] font-semibold uppercase tracking-[.16em] text-primary dark:text-emerald-300">{label}</p><h3 className="mt-1 font-heading text-base font-semibold">{question}</h3></div><p className="text-xs leading-5 text-slate-500 dark:text-slate-400">{answer}</p></article>)}</div></div></section>

      <section className="bg-[#0a2852] px-4 py-14 text-white sm:px-6 sm:py-16 lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-[.38fr_.62fr]"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-emerald-300">The critical handoff</p><h2 className="mt-4 font-heading text-3xl font-semibold leading-tight sm:text-4xl">Checkout is not complete until the learner can begin.</h2><p className="mt-4 text-sm leading-7 text-blue-100">Design the success path and the exceptions. Payment failure, duplicate orders, refunds, expired access, wrong email, and manual collection all need a visible owner.</p></div><div className="grid gap-3 sm:grid-cols-2">{[["01", "Purchase", "Learner identity, selected offer, amount, tax context, and consent are captured."], ["02", "Order", "The payment result creates a traceable commercial record instead of a screenshot."], ["03", "Access", "The correct course and duration attach to the correct learner account."], ["04", "Onboarding", "The learner sees where to start, what to complete, and where to ask for help."]].map(([number, title, text]) => <div key={number} className="rounded-xl border border-white/10 bg-white/[.055] p-4"><span className="font-mono text-[.6rem] text-emerald-300">{number}</span><h3 className="mt-4 font-heading text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-blue-100">{text}</p></div>)}</div></div></div></section>

      <section className="px-4 py-14 sm:px-6 sm:py-16 lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-[.35fr_.65fr]"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-primary dark:text-emerald-300">Launch readiness</p><h2 className="mt-3 font-heading text-3xl font-semibold leading-tight">Publish when the complete path works—not when the uploads finish.</h2><p className="mt-4 text-sm leading-7 text-slate-600 dark:text-slate-300">Run a real test purchase with a fresh email and experience the course as a learner before inviting traffic.</p></div><div className="grid gap-px overflow-hidden rounded-2xl border border-blue-950/10 bg-blue-950/10 sm:grid-cols-2 dark:border-white/10 dark:bg-white/10">{["Program page explains audience, outcome, format, and limits", "Price, tax, coupon, refund, and access rules are confirmed", "Mobile playback, captions, audio, and downloads are checked", "Welcome message and first lesson make the next action obvious", "Support owner can resolve payment and access issues", "Progress and completion rules match the actual course design", "Certificate wording and eligibility are credible", "Analytics and weekly review questions are defined"].map((item, index) => <div key={item} className="flex gap-3 bg-white p-4 text-sm leading-6 dark:bg-[#0b1931]"><span className="grid size-6 shrink-0 place-items-center rounded-full bg-emerald-100 text-[.62rem] font-bold text-emerald-800 dark:bg-emerald-300/10 dark:text-emerald-200">{index + 1}</span>{item}</div>)}</div></div></div></section>

      <section className="border-y border-blue-950/8 bg-[#eef4fb] px-4 py-12 sm:px-6 lg:px-8 dark:border-white/8 dark:bg-[#08172e]"><div className="mx-auto grid max-w-7xl gap-7 lg:grid-cols-[.4fr_.6fr] lg:items-center"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-primary dark:text-emerald-300">Useful planning tools</p><h2 className="mt-3 font-heading text-3xl font-semibold leading-tight">Test the business model before paying for traffic.</h2></div><div className="grid gap-3 sm:grid-cols-3">{[["Course pricing calculator", "/tools/course-pricing-calculator", "Model fee, costs, margin, and enrolments."], ["Profit calculator", "/tools/profit-calculator", "Compare revenue with delivery and marketing costs."], ["Certificate generator", "/tools/certificate-generator", "Prototype completion proof and required details."]].map(([title, href, text]) => <Link key={title} href={href} className="group rounded-xl border border-blue-950/10 bg-white p-4 dark:border-white/10 dark:bg-white/[.04]"><h3 className="font-heading text-base font-semibold">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-500 dark:text-slate-400">{text}</p><span className="mt-4 inline-flex items-center gap-2 text-xs font-semibold text-primary dark:text-emerald-300">Open tool <ArrowRight className="size-3.5 transition group-hover:translate-x-1" /></span></Link>)}</div></div></section>

      <section className="px-4 py-14 sm:px-6 sm:py-16 lg:px-8"><div className="mx-auto grid max-w-7xl gap-9 lg:grid-cols-[.34fr_.66fr]"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-primary dark:text-emerald-300">Recorded-course questions</p><h2 className="mt-3 font-heading text-3xl font-semibold leading-tight">Decisions to make before choosing tools.</h2><div className="mt-6 rounded-2xl border border-blue-950/10 bg-white p-5 dark:border-white/10 dark:bg-white/[.04]"><MessageCircleMore className="size-5 text-primary dark:text-emerald-300" /><p className="mt-4 font-heading text-lg font-semibold">Bring one real course.</p><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">We can map its page, checkout, access, lessons, support, progress, and proof.</p><ProductTourTrigger label="See the recorded-course flow" variant="solid" size="sm" className="mt-5 w-full justify-center" /></div></div><div className="border-t border-blue-950/10 dark:border-white/10">{faqs.map(([question, answer], index) => <details key={question} open={index === 0} className="group border-b border-blue-950/10 py-5 dark:border-white/10"><summary className="flex cursor-pointer list-none items-start justify-between gap-5"><span className="flex gap-3"><span className="mt-1 font-mono text-[.62rem] text-primary/45">0{index + 1}</span><span className="font-heading text-base font-semibold leading-7 sm:text-lg">{question}</span></span><span className="grid size-8 shrink-0 place-items-center rounded-full border border-blue-950/15 text-primary transition group-open:rotate-45 dark:border-white/15 dark:text-emerald-300">+</span></summary><p className="mt-3 max-w-3xl pl-10 pr-10 text-sm leading-7 text-slate-600 dark:text-slate-300">{answer}</p></details>)}</div></div></section>

      <section className="px-4 pb-14 sm:px-6 sm:pb-16 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-6 rounded-[1.5rem] bg-[linear-gradient(110deg,#133f79,#176ca1_58%,#14836d)] p-6 text-white sm:p-8 lg:flex-row lg:items-center lg:justify-between"><div><div className="inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[.18em] text-emerald-200"><Sparkles className="size-4" />Ready to package the first course?</div><h2 className="mt-3 max-w-3xl font-heading text-3xl font-semibold leading-tight">Map one buyer journey and one learner journey before launch.</h2></div><div className="flex shrink-0 flex-col gap-3 sm:flex-row"><ProductTourTrigger label="Plan the KASA workflow" variant="solid" size="sm" className="justify-center" /><Link href="/features/course-selling-platform" className="inline-flex h-10 items-center justify-center gap-2 rounded-full border border-white/20 bg-white/10 px-5 text-sm font-semibold text-white">Explore course selling <ArrowRight className="size-4" /></Link></div></div></section>
    </main>
  </>;
}
